### ISSUE TITLE
when pasted too much text into the view，the view's contentOffset is not correct。Any body know how to fix it

### ISSUE THREAD

**Issue by Michael-iOSer** [hanspinckaers/GrowingTextView#116]
![qq20150501-1 2x](https://cloud.githubusercontent.com/assets/5109679/7428619/50e4839a-f026-11e4-8e4f-31eb5847c62e.png)

**Comment by hiteshvarmora** [comment]
Paste this code in refreshHeight method.

1                 [self resizeTextView:newSizeH];
2  
3                if ([delegate respondsToSelector:@selector(growingTextView:didChangeHeight:)]) {
4                    [delegate growingTextView:self didChangeHeight:newSizeH];
5                }

above this line, 
                  internalTextView.scrollEnabled = YES;

in if condition..

it should work, i tested in iOS 8.

**Comment by Michael-iOSer** [comment]
@hiteshvarmora Thanks for your reply! It works!
