### ISSUE TITLE
Bouncing

### ISSUE THREAD

**Issue by bergusman** [hanspinckaers/GrowingTextView#12]
On iOS 4.3 bouncing doesn't work, if I remove layoutSubviews method it works.

**Comment by dkharrat** [comment]
I'm also seeing this issue on iOS 4.0. The scroll and bounce don't seem to work properly.

**Comment by dkharrat** [comment]
As I commented there, the commit for pull request #7 is what seems to have broke the scrolling/bouncing behavior. This issue can be closed when that commit is reverted.
