### ISSUE TITLE
Does not work in landscape

### ISSUE THREAD

**Issue by aokj4ck** [hanspinckaers/GrowingTextView#2]
When switching to landscape orientation keyboardWillShow: is called again and the HPGrowingTextView flies off-screen.

**Comment by hanspinckaers** [comment]
Thanks, should be a small fix. Will fix it when i have time.

**Comment by auibrian** [comment]
Joe, I've updated my branch to address this issue. You can try from there or wait to see if Hans accepts the pull request.

**Comment by hanspinckaers** [comment]
Pull request accepted.
