### ISSUE TITLE
Can we make first letter in every sentence in CAPITAL letter and turn off auto completed.

### ISSUE THREAD

**Issue by ghost** [hanspinckaers/GrowingTextView#23]

**Comment by gtmtg** [comment]
To make the first letter of each sentence capitalized - `textView.internalTextView.autocapitalizationType = UITextAutocapitalizationTypeSentences;`

To turn off autocorrect - `textView.internalTextView.autocorrectionType = UITextAutocorrectionTypeNo;`

**Comment by ghost** [comment]
Thanks you. i done!
