### ISSUE TITLE
CocoaPods Podspec Outdated

### ISSUE THREAD

**Issue by aggrhm** [hanspinckaers/GrowingTextView#35]
Can you update the .podspec for CocoaPods? Seems to be pointing to an outdated version without placeholder support. Thanks.

**Comment by aggrhm** [comment]
Or really, it looks like the spec at https://github.com/CocoaPods/Specs/blob/master/HPGrowingTextView/0.0.1/HPGrowingTextView.podspec is outdated.

**Comment by mouhcine** [comment]
Until @HansPinckaers adds a tag, it's not possible to add a new spec on CocoaPods repo.

I have the same problem as I need to use the placeholder API. For now the only solution is to specify the last commit in the podfile 

> pod 'HPGrowingTextView', :git => 'https://github.com/HansPinckaers/GrowingTextView.git', :commit => '80b4638258'

**Comment by aggrhm** [comment]
Thanks. Using that pod syntax is good enough for me for now.

**Comment by hanspinckaers** [comment]
Can maybe someone give me an example podspec that could work? Or, if you have time; open a pull req?

**Comment by hanspinckaers** [comment]
Will this work?:

```
Pod::Spec.new do |s|
  s.name         = "HPGrowingTextView"
  s.version      = "0.0.1"
  s.summary      = "Multi-line/Autoresizing UITextView similar to SMS-app."
  s.description  = "An UITextView which grows/shrinks with the text and starts scrolling when the content reaches a certain number of lines."
  s.homepage     = "https://github.com/HansPinckaers/GrowingTextView"
  s.license      = { :type => 'MIT', :file => 'LICENSE.txt' }
  s.author       = { "Hans Pinckaers" => "hans.pinckaers@gmail.com" }
  s.source       = { :git => "https://github.com/HansPinckaers/GrowingTextView.git", :commit => "80b463825808759145080eb66e8fa045ace0bdf6" }
  s.platform     = :ios
  s.source_files = 'Classes', 'class/**/*.{h,m}'
  s.requires_arc = true
end
```

**Comment by mouhcine** [comment]
Here's the documentation on how to create it. There is even a command that would test it.
http://docs.cocoapods.org/specification.html

The main issue is that you should make tags in order for anyone to add the spec to cocoa pods/specs (a thing that anyone can do, but not tags on your repo)

**Comment by mouhcine** [comment]
If you don't have time to create the pod spec, just add a tag (for instance 0.1.0 and I'll make a pull request.

**Comment by aggrhm** [comment]
If master stays relatively stable, could we just point the pod spec at the
master branch? That way you won't have to constantly re-update.

Sent from my iPhone

On Aug 12, 2013, at 5:11 PM, mouhcine notifications@github.com wrote:

Here's the documentation on how to create it. There is even a command that
would test it.

—
Reply to this email directly or view it on
GitHubhttps://github.com/HansPinckaers/GrowingTextView/issues/35#issuecomment-22525730
.
