### ISSUE TITLE
Delete Method Needed to Enable Delete on a Selection 

### ISSUE THREAD

**Issue by Farranco** [hanspinckaers/GrowingTextView#37]
A delete method should be added so that users can delete a selected text:

```
-(IBAction)delete:(id)sender {
    internalTextView.text = [internalTextView.text stringByReplacingCharactersInRange:internalTextView.selectedRange withString:@""];
}
```

It also prevents the delete from cascading down the responder chain and removing a more root object that is attached to the view showing the current text.

**Comment by hanspinckaers** [comment]
Why is this needed? Deleting seems to work fine.

**Comment by Farranco** [comment]
Then it must have been a particular issue in my view hierarchy. Without it there was no delete option after selecting text.

**Comment by hanspinckaers** [comment]
Well I was deleting with backspace.

**Comment by Farranco** [comment]
Deleting with backspace is fine. However, in my case I have another item lower down in the responder chain (a book entry) that will  respond to delete. The delete option is then presented to the user but acts on the whole item instead of the selected text as expected. Hence I added the delete method to GrowingTextView to capture that message. I understand this is particular to my own project and you might not desire the delete option in GrowingTextView. But I thought it might be useful to others as it's presents a bug in this case that is easy to overlook.

![deletebuttons](https://f.cloud.github.com/assets/1274788/1103366/4d98fc6c-18a4-11e3-829a-7fdde2d00b1d.png)
