### ISSUE TITLE
TextView doesn't grow in iOS 7

### ISSUE THREAD

**Issue by adamkmccarthy** [hanspinckaers/GrowingTextView#38]
I've started debugging this to see if I can find out why but in the meantime it doesn't work at all in iOS 7. Working backwards the `growingTextView` delegate call never gets hit. It looks like the textview has trouble figuring out what height it should be.  Have you tried running it in the iOS 7 simulator at all?

Awesome control btw, nicely done.

**Comment by johnpaulmanoza** [comment]
I got same problem.

**Comment by seankellycs** [comment]
I'm running into this same issue. Has anyone found out a fix yet?

**Comment by joeharby** [comment]
Love this plugin, but I'm getting the same issue in iOS 7.

**Comment by PlayDevelop** [comment]
+1 on this problem.

**Comment by wcrtr** [comment]
+1 looking into why this is happening...

**Comment by ghost** [comment]
Folks - FYI it is against the Apple policy to discuss pre-release software on the public Internet. I recommend we shift discussion to the Apple Developer Forums, where there is a thread on this topic if you search for HPGrowingTextView, along with some progress toward a solution.

**Comment by adamkmccarthy** [comment]
No internal or pre release APIs have been discussed here. It is most likely a fix will be pushed by the owner or a contributor and no discussion will need to take place. iOS 7 itself is in the public domain, apple acknowledge this through their own website. All that has happened here is that it's presence has been admitted, nothing more.

Thanks for letting us know this component is being discussed there though. Do you have a link to the topic?

**Comment by adamkmccarthy** [comment]
For anyone curious, the thread referred to above is here. Dev credentials required of course. https://devforums.apple.com/message/872745#872745

**Comment by johnpaulmanoza** [comment]
Issue has been fix from the link above. Thanks @adamkmccarthy.

**Comment by hanspinckaers** [comment]
Awesome, I will check when I have time. But a pull request would certainly help :)

**Comment by johnpaulmanoza** [comment]
Okay I will.

**Comment by hanspinckaers** [comment]
@johnpaulmanoza any updates on the pull req?

**Comment by johnpaulmanoza** [comment]
Just did @HansPinckaers. Sorry for some delays I almost forgotten it.

**Comment by hanspinckaers** [comment]
This should have been fixed now with @johnpaulmanoza pull req and a contentOffset behavior fix.

**Comment by octopepper** [comment]
It look like it is not fix. I just download current version (with @johnpaulmanoza pull req inside) and it change nothing for iOS7 devices and does not run on iOS6 devices.
iOS6 fixes is easy, add a respond to selector, but I'm still without multi-line in iOS7.
Do I am the only one ? I will continue to look what is the issue for me.

**Comment by hanspinckaers** [comment]
Just checked on GM, works on my device :)

**Comment by hanspinckaers** [comment]
Are you sure that you are up to date? Because the building for iOS6 is also fixed.

**Comment by joeharby** [comment]
It works for me on iOS 6 & 7.

**Comment by jonasman** [comment]
not working here also. Do I need to change something? i had an old version

**Comment by octopepper** [comment]
Monday is better to work well. I take care to really download the master last version, and everything work well.
@jonasman you just have to download the last version, and replace your old HPGrowing... files by the new one. Should be working fine on iOS 6 and 7.

**Comment by jonasman** [comment]
i also pulled the latest it works on the example, but not on my project. I was wondering if i need to change some setting. I will try to debug/dig more later

**Comment by badMatters** [comment]
@jonasman I had a similar problem to you. Friday I updated my working copies with the latest version but it made no difference on my devices. I found that when I cleaned my project and deleted it from my devices when I built and tested on the phone it worked. Both on 4G run the ios7GM and on a 3GS running 6.1. Don't know if that helps.

**Comment by jonasman** [comment]
OK i found the issue.
Previously the maxNumberOfLines was set to 3 in the init method but now it is commented out.
 textField.maxNumberOfLines = 3; Solves the problem :)
