### ISSUE TITLE
Can't build using the iOS 6.0 SDK

### ISSUE THREAD

**Issue by kukosk** [hanspinckaers/GrowingTextView#42]
Hi,

Thanks for such a great lib, but I found a small issue when pulling today. You used the method boundingRectWithSize:options:attributes:context which is only available in 7.0 SDK, and now I can't build using 6.0.

**Comment by johnpaulmanoza** [comment]
Hey, there is a method called boundingRectWithSize:options:context from NSAttributedString. You can use that though.

**Comment by hanspinckaers** [comment]
Will fix.
