### ISSUE TITLE
Crash during growDidStop (in the latest version too)

### ISSUE THREAD

**Issue by vernon99** [hanspinckaers/GrowingTextView#44]
I had this crash (reported by Crashlytics) for a while and hoped to fix it with the update to latest version of the controller. Done it few days ago, still happens.
- (void)growDidStop
  {
  if ([delegate respondsToSelector:@selector(growingTextView:didChangeHeight:)]) {
      [delegate growingTextView:self didChangeHeight:self.frame.size.height];
  }
  }

On the first line of code (if [delegate, etc).
Exception Type: EXC_BAD_ACCESS Code: KERN_INVALID_ADDRESS at 0x3520708478
Note: I don't have this selector in my delegate. This bug occured few times for few hundred users.
Could it be that delegate is nil? Do I need to manually set the delegate?

**Comment by hanspinckaers** [comment]
Delegate is unsafe_unretained iirc, hence it won't retain the delegate object. Delegate is not nil here, it is a pointer to an object you already released. So it doesn't exist anymore. You can use the zombies template with Instruments to debug this fairly easy. 

Hans

**Comment by vernon99** [comment]
Thanks! Tried to use zombies, but it didn't help, I haven't find any. This bug is so rare, I'm not sure even how to reproduce. So for now I've just added checks "if (delegate)", I think it makes sense and suggest to use it in the main branch as well.
