### ISSUE TITLE
Crash on iOS 6 when building in XCode 5 against iOS 7

### ISSUE THREAD

**Issue by SRandazzo** [hanspinckaers/GrowingTextView#59]
This commit/PR: https://github.com/HansPinckaers/GrowingTextView/pull/54/files
breaks iOS 6 compatibility,

I'll happily PR a fix back as soon as i'm at my work computer, wanted to document this here for others incase though.

Should be using a run-time check instead of a compiler flag check

the library isn't explicitly iOS 7 only is it?

**Comment by hanspinckaers** [comment]
No this library isn't iOS 7 explicitly :)

**Comment by SRandazzo** [comment]
@HansPinckaers thanks for fixing in you latest commits! just went to resolve my self and was wondering why it wasn't crashing anymore :-0

If the newer methods offer something that fixes iOS 7 behavior we can certainly add them back using run time checks, but if there is no benefit might not be worth implementing now

Thanks for fixing, going to close this issue out as it was it fixed here: https://github.com/HansPinckaers/GrowingTextView/commit/c61f6e807c34b6c55d33d7eecc121bf30263116c
