### ISSUE TITLE
[Bug] Wrong content size

### ISSUE THREAD

**Issue by rokemoon** [hanspinckaers/GrowingTextView#73]
When paste big text, content don't scroll and has some ui bug.
![hpgrowingtext](https://f.cloud.github.com/assets/178757/1571715/872752c8-510a-11e3-84f4-572568526694.png)

**Comment by rokemoon** [comment]
Sorry, you can reproduce this in ios 7.

**Comment by EkkoG** [comment]
#60 #63  had fix this bug.

**Comment by mahboud** [comment]
Typing in a single character after the paste will correct the issue.  (Not a fix but maybe it will provide a clue)

**Comment by proxi** [comment]
I have seen a similar issue on iOS7. The culprit is line #415:

```
internalTextViewFrame.size.width = internalTextView.contentSize.width;
```

which is different width than one set in layoutSubviews (line #133):

```
r.size.width = self.bounds.size.width - contentInset.left - contentInset.right;
```

**Comment by vamsi2r** [comment]
Issue still exists. In iOS7 if I'm pasting text which more than the maximum height of the TextView, Its scrolling to last but one line. But it should scroll to last line.
