### ISSUE TITLE
__IPHONE_7_0 used incorrectly

### ISSUE THREAD

**Issue by smillense** [hanspinckaers/GrowingTextView#78]
- (void)drawRect:(CGRect)rect
  {
  [super drawRect:rect];
  if (self.displayPlaceHolder && self.placeholder && self.placeholderColor)
  {
  #ifdef __IPHONE_7_0
      NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
      paragraphStyle.alignment = self.textAlignment;
      [self.placeholder drawInRect:CGRectMake(5, 8 + self.contentInset.top, self.frame.size.width-self.contentInset.left, self.frame.size.height- self.contentInset.top) withAttributes:@{NSFontAttributeName:self.font, NSForegroundColorAttributeName:self.placeholderColor, NSParagraphStyleAttributeName:paragraphStyle}];
  #else
      [self.placeholderColor set];
      [self.placeholder drawInRect:CGRectMake(8.0f, 8.0f, self.frame.size.width - 16.0f, self.frame.size.height - 16.0f) withFont:self.font];
  #endif
  }
  }

__IPHONE_7_0 is used to determine whether or not on ios7. But this is wrong. It is only a compile time macro. So on XCode 5, it always goes through __IPHONE_7_0 path. If I use XCode to build an ios6 target, it will crash on runtime.
Here, a runtime check is needed. e.g. if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0)

**Comment by hanspinckaers** [comment]
Correct sir!
