### ISSUE TITLE
[iOS6]HPTextViewInternal drawInRect:withattributes:

### ISSUE THREAD

**Issue by uchidaknet** [hanspinckaers/GrowingTextView#80]
I catch a crash on iOS6.
Maybe `NSString drawingRect:withattributes:` is private method in iOS6.
I think that we don't use `respondToSelector:@selector`.

**Comment by hanspinckaers** [comment]
Really? There is a if ([self.placeholder respondsToSelector:@selector(drawInRect:withAttributes:)]) around it. Very strange
