### ISSUE TITLE
[iOS6]HPTextViewInternal drawInRect:withattributes:   crash

### ISSUE THREAD

**Issue by wangjianlewo** [hanspinckaers/GrowingTextView#81]
crash info: -[__NSDictionaryI font]: unrecognized selector sent to instance 0x14806750
2013-12-18 10:58:22.958 iHome[3060:907] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI font]: unrecognized selector sent to instance 0x14806750'
**\* First throw call stack:
(0x21b7012 0x1fdce7e 0x22424bd 0x21a6bbc 0x21a694e 0x15575ad 0x15587c7 0x1ea24b 0x157b4be 0xd13a3f 0xd1396b 0xc25697 0xd1383c 0xd139ba 0xd132b6 0xd13994 0xd080e2 0xd0815c 0xc860bc 0xc87227 0xc878e2 0x217fafe 0x217fa3d 0x215d7c2 0x215cf44 0x215ce1b 0x2b067e3 0x2b06668 0x152b65c 0x1b265d 0x27e5)
libc++abi.dylib: terminate called throwing an exception

**Comment by gzucm** [comment]
Lastest code, but still crash.
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException',reason: '-[__NSArrayM drawInRect:withAttributes:]: unrecognized selector sent to instance 0x17f00870'

Maybe growingTextView.delegate didn't set nil when the class's owner dealloc.
